#parameters:
#    mmi_jub_galerie.example.class: MMI\Jub\GalerieBundle\Example

services:
#    mmi_jub_galerie.example:
#        class: %mmi_jub_galerie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mmi_jub_galerie_user.registration_completed:
         class: MMI\Jub\GalerieBundle\EventListener\RegistrationConfirmListener
         arguments: [@router]
         tags:
              - { name: kernel.event_subscriber }
