<?php

namespace MMI\Jub\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiRepository extends EntityRepository
{
}
